mqtt:
  host: 30.30.45.115
  user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_PASSWORD}'

birdseye:
  enabled: false

detectors:
  cpu1:
    type: cpu
    num_threads: 2
  cpu2:
    type: cpu
    num_threads: 2
  cpu3:
    type: cpu
    num_threads: 2
  cpu4:
    type: cpu
    num_threads: 2

# detectors:
#   ov:
#     type: openvino
#     device: AUTO
#     model:
#       path: /openvino-model/ssdlite_mobilenet_v2.xml

# model:
#   width: 300
#   height: 300
#   input_tensor: nhwc
#   input_pixel_format: bgr
#   labelmap_path: /openvino-model/coco_91cl_bkgr.txt

# <NEW COMMENT
# ffmpeg:
#     hwaccel_args: preset-vaapi
# new comment> 
    # output_args:
    #     record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
    # hwaccel_args: # This is the section for the H/W Accelaration, you will need to figure out what settings you need to enable - https://docs.frigate.video/configuration/hardware_acceleration
       #  -c:v h264_qsv
       # - -hwaccel
       # - vaapi
       # - -hwaccel_device
       # - /dev/dri/renderD128
       # - -hwaccel_output_format
       # - yuv420p

# detect:
#   width: 896
#   height: 672
#   fps: 5

# ffmpeg:
# hwaccel_args: -hwaccel qsv -hwaccel_output_format nv12 -c:v h264_qsv
# input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000
#   output_args:
#     # record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
# record: preset-record-generic-audio-copy

go2rtc:
  streams:
    #     # working config
    #  uses for a live with audio
    front_door_mse:
      #     - rtsp://{FRIGATE_USER}:{FRIGATE_PASSWORD}@{FRIGATE_IP_CAM_FRONT_DOOR}:554/cam/realmonitor?channel=1&subtype=2
      - rtsp://{FRIGATE_USER}:{FRIGATE_PASSWORD}@{FRIGATE_IP_CAM_FRONT_DOOR}:554/h264Preview_01_sub
      - ffmpeg:front_door#audio=aac
    outside_front:
      - rtsp://{FRIGATE_USER}:{FRIGATE_PASSWORD}@{FRIGATE_IP_CAM_OUTSIDE_FRONT}:554/h264Preview_01_sub
      - ffmpeg:outside_front#audio=aac
    # #0001 remove me in case front door camera not works well for any reasons
    front_door:
      - http://{FRIGATE_IP_CAM_FRONT_DOOR}/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_USER}&password={FRIGATE_PASSWORD}
      - ffmpeg:your_reolink_camera#audio=opus
    front_door_sub:
      - http://{FRIGATE_IP_CAM_FRONT_DOOR}/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_USER}&password={FRIGATE_PASSWORD}

cameras:
  # #0002 restore me
  front_door_backup:
    detect:
      width: 640
      height: 360
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: 'rtsp://{FRIGATE_USER}:{FRIGATE_PASSWORD}@{FRIGATE_IP_CAM_FRONT_DOOR}:554/h264Preview_01_main'
          roles:
            - record
        - path: 'rtsp://{FRIGATE_USER}:{FRIGATE_PASSWORD}@{FRIGATE_IP_CAM_FRONT_DOOR}:554/h264Preview_01_sub'
          roles:
            # - rtmp
            - detect

  # This is buggy, time to time is beying unresponsive - reolink issue I guess
  # #0001 remove me in case front door camera not works well for any reasons; and restore #0002
  # front_door:
  #   zones:
  #     door_bell:
  #       coordinates: 191,42,432,208,457,360,86,360
  #       objects:
  #         - person
  #   detect:
  #     width: 640
  #     height: 360
  #   live:
  #     stream_name: front_door_mse
  #   ffmpeg:
  #     output_args:
  #       record: preset-record-generic-audio-copy
  #     inputs:
  #       - path: rtsp://127.0.0.1:8554/front_door?video=copy&audio=copy
  #         input_args: preset-rtsp-restream
  #         roles:
  #           - record
  #       - path: rtsp://127.0.0.1:8554/front_door_sub?video=copy&audio=copy
  #         input_args: preset-rtsp-restream
  #         roles:
  #           - detect

  outside_front:
    zones:
      parking:
        coordinates: 
          47,176,186,174,355,172,433,172,546,177,640,168,640,107,474,74,309,72,167,69,91,81,43,93,29,105,0,118,0,136,0,191
      sidewalk:
        coordinates: 
          37,291,175,315,429,314,551,302,640,279,640,225,560,237,490,245,454,247,367,253,304,261,207,245,116,240,0,226
    detect:
      width: 640
      height: 360
      fps: 5
        # Optional: Number of frames without a detection before Frigate considers an object to be gone. (default: 5x the frame rate)
      max_disappeared: 25
      stationary:
        # Optional: Frequency for confirming stationary objects (default: shown below)
        # When set to 0, object detection will not confirm stationary objects until movement is detected.
        # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
        interval: 1
        # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
        threshold: 50
        # Optional: Define a maximum number of frames for tracking a stationary object (default: not set, track forever)
        # This can help with false positives for objects that should only be stationary for a limited amount of time.
        # It can also be used to disable stationary object tracking. For example, you may want to set a value for person, but leave
        # car at the default.
        # WARNING: Setting these values overrides default behavior and disables stationary object tracking.
        #          There are very few situations where you would want it disabled. It is NOT recommended to
        #          copy these values from the example config into your config unless you know they are needed.
        max_frames:
          # Optional: Default for all object types (default: not set, track forever)
          default: 3000
          # Optional: Object specific values
          objects:
            person: 1000
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        # - path: rtsp://127.0.0.1:8554/outside_front
        #   input_args: preset-rtsp-restream
        #   roles:
        #   - record
        #   - detect
        - path: 
            rtsp://{FRIGATE_USER}:{FRIGATE_PASSWORD}@{FRIGATE_IP_CAM_OUTSIDE_FRONT}:554/h264Preview_01_main
          roles:
            - record
        - path: 
            rtsp://{FRIGATE_USER}:{FRIGATE_PASSWORD}@{FRIGATE_IP_CAM_OUTSIDE_FRONT}:554/h264Preview_01_sub
          roles:
            # - rtmp
            - detect

record:
  enabled: true
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  retain:
      # Optional: Number of days to retain recordings regardless of events (default: shown below)
      # NOTE: This should be set to 0 and retention should be defined in events section below
      #       if you only want to retain recordings of events.
      days: 0
      # Optional: Mode for retention. Available options are: all, motion, and active_objects
      #   all - save all recording segments regardless of activity
      #   motion - save all recordings segments with any detected motion
      #   active_objects - save all recording segments with active/moving objects
      # NOTE: this mode only applies when the days setting above is greater than 0
      mode: all
  events:
    pre_capture: 10
    post_capture: 10
    retain:
      default: 21
      mode: motion

# Optional: Live stream configuration for WebUI
# NOTE: Can be overridden at the camera level
live:
  # Optional: Set the height of the live stream. (default: 720)
  # This must be less than or equal to the height of the detect stream. Lower resolutions
  # reduce bandwidth required for viewing the live stream. Width is computed to match known aspect ratio.
  height: 720
  # Optional: Set the encode quality of the live stream (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 20

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - bicycle
    - car
    - motorcycle
    - bus

telemetry:
  # Optional: Enable the latest version outbound check (default: shown below)
  # NOTE: If you use the HomeAssistant integration, disabling this will prevent it from reporting new versions
  version_check: false

# ffmpeg:
#   hwaccel_args:
#     - -hwaccel
#     - qsv
#     - -qsv_device
#     - /dev/dri/renderD128

environment_vars:
  LIBVA_DRIVER_NAME: iHD
version: 0.14
